language: haskell
ghc:
  - 7.6
  - 7.8

before_install:
  - cabal update
  - cabal install 'cartel ==0.10.2.0' packdeps
  - pwd
  - sh generate
  - packdeps quickpull.cabal

install:
  - cabal install --only-dependencies

script:
  - ghc-pkg list
  - cabal sdist --output-directory=tarball
  - cd tarball
  - pwd
  - cabal install
